bookmark/urls.py
from django.urls import path

from bookmark.views import ListCreateView, BookmarkListView, \
    ListUpdateView, ItemListView, ItemCreateView, ItemDeleteView, ItemDetailView, ItemUpdateView, \
    PublicBookmarkListView, PublicItemListView, ListDeleteView, register_favorite_list, delist_favorite_list, \
    register_favorite_item, delist_favorite_item, follow_user, unfollow_user
from config.library.views import custom_login_required
# ToDo: LoginRequiredMixin Redirect to login_success view

app_name = "bookmark"

urlpatterns = [
    path('', BookmarkListView.as_view(), name="index"),
    path('add/', ListCreateView.as_view(), name="add_list"),
    path('update/<int:pk>/', ListUpdateView.as_view(), name="update_list"),
    path('delete/<int:pk>/', ListDeleteView.as_view(), name="delete_list"),

    path('<int:pk>/', ItemListView.as_view(), name="item_list"),
    path('<int:pk>/add/', ItemCreateView.as_view(), name="add_item"),
    path('<int:list_pk>/delete/<int:pk>/', ItemDeleteView.as_view(), name="delete_item"),
    path('<int:list_pk>/detail/<int:pk>/', ItemDetailView.as_view(), name="item_detail"),
    path('<int:list_pk>/update/<int:pk>/', ItemUpdateView.as_view(), name="update_item"),

    path('<str:nickname>/', PublicBookmarkListView.as_view(), name='public_list'),
    path('<str:nickname>/<int:pk>/', PublicItemListView.as_view(), name='public_item_list'),
    path('<str:nickname>/<int:list_pk>/detail/<int:pk>/', ItemDetailView.as_view(), name="public_item_detail"),

    path('<str:nickname>/<int:pk>/like-this/', register_favorite_list, name="register_favorite_list"),
    path('<str:nickname>/<int:pk>/unlike-this/', delist_favorite_list, name="delist_favorite_list"),
    path('<str:nickname>/<int:list_pk>/<int:pk>/like-this/', register_favorite_item, name="register_favorite_item"),
    path('<str:nickname>/<int:list_pk>/<int:pk>/unlike-this/', delist_favorite_item, name="delist_favorite_item"),

    path('<str:nickname>/follow/', follow_user, name='follow_user'),
    path('<str:nickname>/unfollow/', unfollow_user, name="unfollow_user"),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import app_index.urls as app_index_urls
import bookmark.urls as bookmark_urls
import accounts.urls as accounts_urls
from config import settings

urlpatterns = [
    path('', include(app_index_urls)),
    path('admin/', admin.site.urls),
    path('accounts/', include(accounts_urls)),
    path('bookmark/', include(bookmark_urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmark/models.py
from django.db import models
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from accounts.models import UserProfile


class BookmarkList(models.Model):
    user = models.ManyToManyField(UserProfile, related_name='own_list')

    list_name = models.CharField(_("리스트 이름"), max_length=50)
    description = models.CharField(_("설명"), max_length=255)

    ACCESS_LEVEL_CHOICES = (
        ('P', _('개인')),
        ('S', _('공개')),
    )
    access_level = models.CharField(
        _("접근 권한"),
        max_length=1,
        choices=ACCESS_LEVEL_CHOICES,
        default='P',
    )

    created_at = models.DateTimeField(_("생성 시간"), auto_now_add=True)
    updated_at = models.DateTimeField(_("수정 시간"), auto_now=True)

    def __str__(self):
        return '<' + self.list_name + '> ' + self.description


class BookmarkItem(models.Model):
    belonged_list = models.ForeignKey(BookmarkList, on_delete=models.CASCADE)

    site_name = models.CharField(_("사이트 이름"), max_length=50)
    site_url = models.URLField("URL")

    created_at = models.DateTimeField(_("생성 시간"), auto_now_add=True)
    updated_at = models.DateTimeField(_("수정 시간"), auto_now=True)

    def __str__(self):
        return self.site_name

    def get_absolute_url(self):
        return reverse_lazy('bookmark:detail', args=[self.id])
        # TODO: CBV에서 처리할 수 있는 방법은 없는가 - get_success_url 오버라이딩

bookmark/forms.py
from django import forms

from bookmark.models import BookmarkItem, BookmarkList
from config.library.forms import add_style


class ListForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(forms.ModelForm, self).__init__(*args, **kwargs)

        add_style(self.fields)

    class Meta:
        model = BookmarkList
        fields = ['list_name', 'description', 'access_level']


class ItemForm(forms.ModelForm):
    site_name = forms.CharField(
        max_length=50,
        label='사이트 이름',
        widget=forms.TextInput(
            attrs={'class': 'form-control mt-2'},
        ),
    )
    site_url = forms.URLField(
        label='URL',
        widget=forms.URLInput(
            attrs={'class': 'form-control mt-2'},
        ),
    )

    class Meta:
        model = BookmarkItem
        fields = ['site_name', 'site_url']
        # TODO: add validator

bookmark/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import get_list_or_404, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView

from accounts.models import UserProfile, Follower
from bookmark.forms import ListForm, ItemForm
from bookmark.models import BookmarkItem, BookmarkList


class BookmarkListView(ListView):
    model = BookmarkList
    template_name = "bookmark/bookmark_list.html"
    paginate_by = 6

    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            queryset = BookmarkList.objects.filter(user=self.request.user)
            return queryset
        else:
            # TODO: 임시 방편
            return []

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        _user = self.request.user

        if _user.is_authenticated:
            context['follower_cnt'] = Follower.objects.filter(following=_user).count()

        return context



class ListCreateView(LoginRequiredMixin, CreateView): # ToDo: login success로 redirect
    model = BookmarkList
    template_name = 'bookmark/list_add.html'
    form_class = ListForm
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        _is_valid = super(ListCreateView, self).form_valid(form)
        if _is_valid:
            _list = form.instance
            _list.user.set([self.request.user])

        return _is_valid


class ListUpdateView(LoginRequiredMixin, UpdateView):
    model = BookmarkList
    template_name = 'bookmark/list_update.html'
    form_class = ListForm
    success_url = reverse_lazy('bookmark:index')


class ListDeleteView(LoginRequiredMixin, DeleteView):
    model=BookmarkList,
    success_url=reverse_lazy('bookmark:index'),
    template_name='bookmark/list_confirm_delete.html',


class ItemListView(ListView):
    model = BookmarkItem
    template_name = "bookmark/item_list.html"
    paginate_by = 6

    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated:
            queryset = BookmarkItem.objects.filter(belonged_list=self.kwargs['pk'])
            return queryset
        else:
            # TODO: 임시 방편
            return []

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        _user = self.request.user

        context['url_list_pk'] = self.kwargs.get('pk')
        if _user.is_authenticated:
            context['follower_cnt'] = Follower.objects.filter(following=_user).count()

        return context


class ItemCreateView(LoginRequiredMixin, CreateView):
    model = BookmarkItem
    template_name = 'bookmark/item_add.html'
    form_class = ItemForm

    def get_success_url(self):
        return reverse_lazy(
            'bookmark:item_list',
            args=[self.kwargs.get('pk')],
        )

    def form_valid(self, form):
        list_pk = self.kwargs.get('pk')
        form.instance.belonged_list = BookmarkList.objects.get(pk=list_pk)
        return super(ItemCreateView, self).form_valid(form)


class ItemDetailView(LoginRequiredMixin, DetailView):
    model = BookmarkItem
    template_name = 'bookmark/item_detail.html'


class ItemUpdateView(LoginRequiredMixin, UpdateView):
    model = BookmarkItem
    template_name = 'bookmark/item_update.html'
    form_class = ItemForm

    def get_success_url(self):
        return reverse_lazy(
            'bookmark:item_list',
            args=[self.kwargs.get('pk')],
        )


class ItemDeleteView(LoginRequiredMixin, DeleteView):
    model = BookmarkItem
    template_name = 'bookmark/item_confirm_delete.html'

    def get_success_url(self):
        return reverse_lazy(
            'bookmark:item_list',
            args=[self.kwargs.get('list_pk')],
        )


class PublicBookmarkListView(ListView):
    model = BookmarkList
    template_name = "bookmark/public_bookmark_list.html"
    paginate_by = 6

    def get_queryset(self):
        _user = UserProfile.objects.filter(nickname=self.kwargs.get('nickname')).get()
        if _user:
            queryset = get_list_or_404(BookmarkList, user=_user, access_level='S')
            return queryset
        else:
            # TODO: 임시 방편
            return []

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        _nickname = self.kwargs.get('nickname')
        _user = self.request.user
        _owner = UserProfile.objects.filter(nickname=_nickname).get()
        _list = context['object_list']

        context['follower_cnt'] = Follower.objects.filter(following=_owner).count()
        context['url_nickname'] = _nickname
        context['is_following'] = _user.is_following(_nickname)

        _is_list_fan = dict()
        for item in _list:
            _is_list_fan[item.pk] = _user.is_list_fan(item.pk)

        context['is_fan'] = _is_list_fan

        return context


class PublicItemListView(ListView):
    model = BookmarkList
    template_name = "bookmark/public_item_list.html"
    paginate_by = 6

    def get_queryset(self):
        _user = UserProfile.objects.filter(nickname=self.kwargs.get('nickname')).get()
        if _user:
            _list = get_object_or_404(
                BookmarkList,
                user=_user,
                access_level='S',
                id=self.kwargs.get('pk')
            )
            queryset = _list.bookmarkitem_set.all()
            return queryset
        else:
            # TODO: 임시 방편
            return []

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        _nickname = self.kwargs.get('nickname')
        _user = self.request.user

        context['url_list_pk'] = self.kwargs.get('pk')
        context['url_nickname'] = self.kwargs.get('nickname')
        context['is_following'] = _user.is_following(_nickname)

        return context


def register_favorite_list(request, **kwargs):
    if request.method == "POST":
        user = request.user
        _list = get_object_or_404(BookmarkList, pk=request.POST['list_pk'])

        if _list.user.get() != user:
            _list.fan_of_list.add(user)

            return JsonResponse({
                'cnt': _list.fan_of_list.count()
            })

    return JsonResponse(
        {'status':'false','message': 'register 안돼요'},
        status=500
    )


def delist_favorite_list(request, **kwargs):
    if request.method == "POST":
        user = request.user
        result = user.is_list_fan(request.POST['list_pk'])

        if result and result['is_fan']:
            fan_list = result['list'].fan_of_list
            fan_list.remove(user)

            return JsonResponse({
                'cnt': fan_list.count()
            })

    return JsonResponse(
        {'status':'false','message': 'delist 실패'},
        status=500
    )

def register_favorite_item(request, **kwargs):
    if request.method == "POST":
        user = request.user
        _item = get_object_or_404(BookmarkItem, pk=request.POST['item_pk'])

        if _item.belonged_list.user.get() != user:
            _item.fan_of_item.add(user)

            return JsonResponse({
                'cnt': _item.fan_of_item.count()
            })

    return JsonResponse(
        {'status':'false','message': 'register 안돼요'},
        status=500
    )


def delist_favorite_item(request, **kwargs):
    if request.method == "POST":
        user = request.user
        result = user.is_item_fan(request.POST['item_pk'])

        if result and result['is_fan']:
            fan_list = result['item'].fan_of_item
            fan_list.remove(user)

            return JsonResponse({
                'cnt': fan_list.count()
            })

    return JsonResponse(
        {'status':'false','message': 'delist 실패'},
        status=500
    )


def follow_user(request, nickname):
    _user = request.user
    if request.method == "POST" and _user.nickname != nickname:
        if not _user.is_following(nickname):
            _followed = UserProfile.objects.filter(nickname=nickname).get()

            print(_followed.nickname)

            follow = Follower(following=_followed, follower=_user)
            follow.save()

            return JsonResponse({
                'cnt': Follower.objects.filter(following=_followed).count()
            })

    return JsonResponse(
        {'status': 'false', 'message': 'follow 실패'},
        status=500
    )


def unfollow_user(request, nickname):  # ToDo: 코드 형식이 너무 비슷해 보임, 실패 메시지 제대로
    _user = request.user
    if request.method == "POST":
        if _user.is_following(nickname):
            _followed = UserProfile.objects.filter(nickname=nickname).get()

            follow = Follower.objects.filter(following=_followed, follower=_user)
            follow.delete()

            return JsonResponse({
                'cnt': Follower.objects.filter(following=_followed).count()
            })

    return JsonResponse(
        {'status': 'false', 'message': 'unfollow 실패'},
        status=500
    )

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}
{% block title %}{{ block.super }}-내 북마크 목록{% endblock %}
{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'bookmark/css/bookmark_list.css' %}"/>
{% endblock %}
{% block content %}
<div class="container">
    {% if messages %}
        {% for message in messages %}
            <script>alert('{{ message }}');</script>
        {% endfor %}
    {% endif %}

    <div class="d-flex justify-content-end">
        <a href="{% url 'bookmark:add_list' %}" class="btn btn-info mb-3">
            <i class="fas fa-pencil-alt" style="padding: 0.2rem;"></i> 추가하기
        </a>
    </div>

    <div class="mb-4 text-white">
        <div class="p-1 d-inline-block text-center" style="width: 4rem; background: #34e89e;">공개</div>
        <div class="bg-warning p-1 d-inline-block text-center" style="width: 4rem; background: linear-gradient(90deg,#F2994A,#F2C94C);">비공개</div>
    </div>

    <div class="mb-2">
        팔로워: {{ follower_cnt }}
    </div>

    <div class="card-columns mb-3">
        {% for bookmark_list in object_list %}
            <div class="card
                {% if bookmark_list.access_level == 'P' %}private{% else %}share{% endif %}">
                <div class="card-header text-white px-2">
                    {% with profile_image_url=bookmark_list.user.get.profile_image.url %}
                        {% if profile_image_url == '/media/profile_images/no_image.png' %}
                            <i class="fas fa-user-circle align-middle px-2" style="font-size: 2em;"></i>
                        {% else %}
                            <img src="{{ bookmark_list.user.get.profile_image.url }}" width="50" height="50" class="rounded-circle" />
                        {% endif %}
                    {% endwith %}
                    <span class="align-middle">{{ bookmark_list.user.get.nickname }}</span>
                </div>
                <div onclick="location.href='{% url 'bookmark:item_list' bookmark_list.id %}';" class="card-body pl-3" style="text-decoration: none;">
                    <h5 class="card-title mb-4">{{ bookmark_list.list_name }}</h5>
                    <h6 class="card-subtitle mb-4 text-muted">
                        생성 : {{ bookmark_list.created_at }}<br/>
                        수정 : {{ bookmark_list.updated_at }}
                    </h6>
                    <p class="card-text">{{ bookmark_list.description }}</p>
                </div>
                <div class="card-footer" style="height: 3.5rem; position: relative; font-size: 1.3rem;">
                    <div class="d-inline-block" style="position: absolute; left: 1em;">
                        <i class="
                            {% if bookmark_list.fan_of_list.count %}
                                fas
                            {% else %}
                                far
                            {% endif %}
                            fa-heart p-0" style="color: red; padding: 0.2rem;"></i>
                        <small style="font-size: 0.8rem;">{{ bookmark_list.fan_of_list.count }}</small>
                    </div>
                    <div class="d-inline-block text-right" style="position: absolute; right: 1em;">
                        <i class="fas fa-share-alt" style="padding: 0.2rem;"></i>
                        <a href="{% url 'bookmark:update_list' bookmark_list.id %}" style="text-decoration: none;" class="text-dark">
                            <i class="fas fa-pencil-alt" style="padding: 0.2rem;"></i>
                        </a>
                        <a href="{% url 'bookmark:delete_list' bookmark_list.id %}" style="text-decoration: none;" class="text-dark">
                            <i class="far fa-trash-alt" style="padding: 0.2rem;"></i>
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    {% load bookmark_extra %}

    <ul class="pagination pagination-sm justify-content-center mb-4">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="/bookmark/?page={{ page_obj.previous_page_number }}">previous</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">previous</a>
            </li>
        {% endif %}
        {% for page_num in page_obj.number|prange:page_obj.paginator.num_pages %}
            {% if page_num == page_obj.number %}
                <li class="page-item disabled">
                    <a class="page-link" href="/bookmark/?page={{ page_num }}">{{ page_num }}</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="/bookmark/?page={{ page_num }}">{{ page_num }}</a>
                </li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="/bookmark/?page={{ page_obj.next_page_number }}">next</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">next</a>
            </li>
        {% endif %}
    </ul>
</div>
{% endblock %}
{% block scripts %}
    <script>
        p = $('.private');
        s = $('.share');

        p.addClass('border-warning');
        s.css('border', '1px solid #34e89e')

        p = $('.private .card-header'); //, .private .card-footer');
        s = $('.share .card-header'); //, .share .card-footer');

        p.css('background', 'linear-gradient(90deg,#F2994A,#F2C94C)');
        s.css('background', '#34e89e');

        //p.addClass('bg-warning text-white');
        //s.addClass('bg-primary text-white');
        
        $('.card-body').css( 'cursor', 'pointer' ).hover(function () {
            var footer = $(this).next();

            if($(this).parent().hasClass('private')) {
                footer.addClass('private-card-hover');
            } else {
                footer.addClass('public-card-hover');
            }

            var childrens = [footer.children(), footer.find('a')];
            for(let i=0; i<childrens.length; i++) {
                for(let j=0; j<childrens[i].length; j++) {
                    $(childrens[i][j]).addClass('text-white');
                    $(childrens[i][j]).removeClass('text-dark');
                }
            }
        }, function () {
            var footer = $(this).next();

            if($(this).parent().hasClass('private')) {
                $(this).next().removeClass('private-card-hover');
            } else {
                $(this).next().removeClass('public-card-hover');
            }

            var childrens = [footer.children(), footer.find('a')];
            for(let i=0; i<childrens.length; i++) {
                for(let j=0; j<childrens[i].length; j++) {
                    $(childrens[i][j]).addClass('text-dark');
                    $(childrens[i][j]).removeClass('text-white');
                }
            }
        });
    </script>
{% endblock %}

bookmark/templates/bookmark/item_add.html
{% extends 'form_base.html' %}
{% block title %}{{ block.super }}-추가{% endblock %}
{% block content %}
    <div class="container">
        {% include 'back_button.html' %}

        {% with '추가' as button_value %}
            {{ block.super }}
        {% endwith %}
    </div>
{% endblock %}

bookmark/templates/bookmark/item_confirm_delete.html
{% extends 'base.html' %}
{% block title %}{{ block.super }}-삭제{% endblock %}
{% block content %}
    <div class="container">
        {% include 'back_button.html' %}

        <form method="post">
            {% csrf_token %}

            <div class="alert alert-danger">
                "{{ object }}"?<br/>
                이거 정말 삭제할꾸야?-?
            </div>
            <input type="submit" value="삭제" class="btn btn-danger" />
        </form>
    </div>
{% endblock %}

bookmark/templates/bookmark/item_detail.html
{% extends 'base.html' %}
{% block title %}{{ block.super }}-조회{% endblock %}
{% block content %}
    <div class="container">
        {% include 'back_button.html' %}

        <table class="table">
            <thead>
                <tr>
                    <th>사이트 이름</th>
                    <th>URL</th>
                    <th>생성 시간</th>
                    <th>수정 시간</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ object.site_name }}</td>
                    <td>
                        <a href="{{ object.site_url }}" target="_blank">
                            {{ object.site_url }}
                        </a>
                    </td>
                    <td>{{ object.created_at }}</td>
                    <td>{{ object.updated_at }}</td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}

bookmark/templates/bookmark/item_list.html
{% extends 'base.html' %}
{% block title %}{{ block.super }}-아이템{% endblock %}
{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'bookmark/css/item_list.css' %}"/>
{% endblock %}
{% block content %}
<div class="container">
    {% include 'back_button.html' %}

    <div class="d-flex justify-content-end">
        <a href="{% url 'bookmark:add_item' url_list_pk %}" class="btn btn-info mb-3">
            <i class="fas fa-pencil-alt" style="padding: 0.2rem;"></i> 추가하기
        </a>
    </div>

    <div class="mb-2">
        팔로워: {{ follower_cnt }}
    </div>

    <div class="card-columns mb-3">
        {% for bookmark in object_list %}
            <div class="card" style="border: 1px solid #34e89e">
                <div class="card-header px-2 text-white" style="background-color: #34e89e;">
                    {% with profile_image_url=bookmark.belonged_list.user.get.profile_image.url %}
                        {% if profile_image_url == '/media/profile_images/no_image.png' %}
                            <i class="fas fa-user-circle align-middle px-2" style="font-size: 2em;"></i>
                        {% else %}
                            <img src="{{ bookmark_list.user.get.profile_image.url }}" width="30" height="30" class="rounded" />
                        {% endif %}
                    {% endwith %}
                    <span class="align-middle">{{ bookmark.site_name }}</span>
                </div>
                <div onclick="location.href='{% url 'bookmark:item_detail' list_pk=url_list_pk pk=bookmark.id %}';" class="card-body pl-3" style="text-decoration: none;">
                    <!--<h5 class="card-title mb-4">{{ bookmark_list.list_name }}</h5>-->
                    <h6 class="card-subtitle mb-4 text-muted">
                        생성 : {{ bookmark.created_at }}<br/>
                        수정 : {{ bookmark.updated_at }}
                    </h6>
                    <p class="card-text">
                        <a href="{{ bookmark.site_url }}" target="_blank" onclick="event.stopPropagation();">
                            {{ bookmark.site_url }}
                        </a>
                    </p>
                </div>
                <div class="card-footer" style="height: 3.5rem; position: relative; font-size: 1.3rem;">
                    <div class="d-inline-block" style="position: absolute; left: 1em;">
                        <i class="
                            {% if bookmark.fan_of_item.count %}
                                fas
                            {% else %}
                                far
                            {% endif %}
                            fa-heart p-0" style="color: red; padding: 0.2rem;"></i>
                        <small style="font-size: 0.8rem;">{{ bookmark.fan_of_item.count }}</small>
                    </div>
                    <div class="d-inline-block text-right" style="position: absolute; right: 1em;">
                        <i class="fas fa-share-alt" style="padding: 0.2rem;"></i>
                        <a href="{% url 'bookmark:update_item' list_pk=url_list_pk pk=bookmark.id %}" style="text-decoration: none;" class="text-dark">
                            <i class="fas fa-pencil-alt" style="padding: 0.2rem;"></i>
                        </a>
                        <a href="{% url 'bookmark:delete_item' list_pk=url_list_pk pk=bookmark.id %}" style="text-decoration: none;" class="text-dark">
                            <i class="far fa-trash-alt" style="padding: 0.2rem;"></i>
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    {% load bookmark_extra %}

    {% with list_pk=url_list_pk %}
        <ul class="pagination pagination-sm justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="/bookmark/{{ list_pk }}/?page={{ page_obj.previous_page_number }}">
                            previous
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">previous</a>
                    </li>
                {% endif %}
                {% for page_num in page_obj.number|prange:page_obj.paginator.num_pages %}
                    {% if page_num == page_obj.number %}
                        <li class="page-item disabled">
                            <a class="page-link" href="/bookmark/{{ list_pk }}/?page={{ page_num }}">
                                {{ page_num }}
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="/bookmark/{{ list_pk }}/?page={{ page_num }}">
                                {{ page_num }}
                            </a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="/bookmark/{{ list_pk }}/?page={{ page_obj.next_page_number }}">
                            next
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">next</a>
                    </li>
                {% endif %}
        </ul>
    {% endwith %}
</div>
{% endblock %}
{% block scripts %}
    <script>
        $('.card-body').css( 'cursor', 'pointer' ).hover(function () {
            var footer = $(this).next();

            footer.addClass('card-hover');

            var childrens = [footer.children(), footer.find('a')];
            for(let i=0; i<childrens.length; i++) {
                for(let j=0; j<childrens[i].length; j++) {
                    $(childrens[i][j]).addClass('text-white');
                    $(childrens[i][j]).removeClass('text-dark');
                }
            }
        }, function () {
            var footer = $(this).next();

            footer.removeClass('card-hover');

            var childrens = [footer.children(), footer.find('a')];
            for(let i=0; i<childrens.length; i++) {
                for(let j=0; j<childrens[i].length; j++) {
                    $(childrens[i][j]).removeClass('text-white');
                    $(childrens[i][j]).addClass('text-dark');
                }
            }
        });
    </script>
{% endblock %}

bookmark/templates/bookmark/item_update.html
{% extends 'form_base.html' %}
{% block title %}{{ block.super }}-수정{% endblock %}
{% block content %}
    <div class="container">
        {% include 'back_button.html' %}

        {% with '수정' as button_value %}
            {{ block.super }}
        {% endwith %}
    </div>
{% endblock %}

bookmark/templates/bookmark/list_add.html
{% extends 'form_base.html' %}
{% block title %}{{ block.super }}-추가{% endblock %}
{% block content %}
    <div class="container">
        {% include 'back_button.html' %}

        {% with '추가' as button_value %}
            {{ block.super }}
        {% endwith %}
    </div>
{% endblock %}

bookmark/templates/bookmark/list_confirm_delete.html
{% extends 'base.html' %}
{% block title %}{{ block.super }}-리스트 삭제{% endblock %}
{% block content %}
    <div class="container">
        {% include 'back_button.html' %}

        <form method="post">
            {% csrf_token %}

            <div class="alert alert-danger">
                "{{ object }}"<br/>
                이거 정말 삭제할랭? ㅠ_ㅠ
            </div>
            <input type="submit" value="삭제" class="btn btn-danger" />
        </form>
    </div>
{% endblock %}

bookmark/templates/bookmark/list_update.html
{% extends 'form_base.html' %}
{% block title %}{{ block.super }}-수정{% endblock %}
{% block content %}
    <div class="container">
        {% include 'back_button.html' %}

        {% with '수정' as button_value %}
            {{ block.super }}
        {% endwith %}
    </div>
{% endblock %}