accounts/urls.py
from django.urls import path, reverse_lazy

from accounts.views import LoginView, LogoutView, logout_success, RegistrationView, register_success, \
    CustomPWChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from config.library.views import custom_user_passes_test, custom_login_required

app_name = 'accounts'

urlpatterns = [
    # path('', accounts_views.index, name="index"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('logout-success/', logout_success, name="logout_success"),
    path('register/', RegistrationView.as_view(), name="register"),
    path('register-success/', register_success, name="register_success"),

    path('password-change/', CustomPWChangeView.as_view(), name="password_change"),
    path('password-change/done/', PasswordChangeDoneView.as_view(), name="password_change_done"),

    path('password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset/done/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

bookmark/urls.py
from django.urls import path

from bookmark.views import ListCreateView, BookmarkListView, \
    ListUpdateView, ItemListView, ItemCreateView, ItemDeleteView, ItemDetailView, ItemUpdateView, \
    PublicBookmarkListView, PublicItemListView, ListDeleteView, register_favorite_list, delist_favorite_list, \
    register_favorite_item, delist_favorite_item, follow_user, unfollow_user
from config.library.views import custom_login_required
# ToDo: LoginRequiredMixin Redirect to login_success view

app_name = "bookmark"

urlpatterns = [
    path('', BookmarkListView.as_view(), name="index"),
    path('add/', ListCreateView.as_view(), name="add_list"),
    path('update/<int:pk>/', ListUpdateView.as_view(), name="update_list"),
    path('delete/<int:pk>/', ListDeleteView.as_view(), name="delete_list"),

    path('<int:pk>/', ItemListView.as_view(), name="item_list"),
    path('<int:pk>/add/', ItemCreateView.as_view(), name="add_item"),
    path('<int:list_pk>/delete/<int:pk>/', ItemDeleteView.as_view(), name="delete_item"),
    path('<int:list_pk>/detail/<int:pk>/', ItemDetailView.as_view(), name="item_detail"),
    path('<int:list_pk>/update/<int:pk>/', ItemUpdateView.as_view(), name="update_item"),

    path('<str:nickname>/', PublicBookmarkListView.as_view(), name='public_list'),
    path('<str:nickname>/<int:pk>/', PublicItemListView.as_view(), name='public_item_list'),
    path('<str:nickname>/<int:list_pk>/detail/<int:pk>/', ItemDetailView.as_view(), name="public_item_detail"),

    path('<str:nickname>/<int:pk>/like-this/', register_favorite_list, name="register_favorite_list"),
    path('<str:nickname>/<int:pk>/unlike-this/', delist_favorite_list, name="delist_favorite_list"),
    path('<str:nickname>/<int:list_pk>/<int:pk>/like-this/', register_favorite_item, name="register_favorite_item"),
    path('<str:nickname>/<int:list_pk>/<int:pk>/unlike-this/', delist_favorite_item, name="delist_favorite_item"),

    path('<str:nickname>/follow/', follow_user, name='follow_user'),
    path('<str:nickname>/unfollow/', unfollow_user, name="unfollow_user"),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import app_index.urls as app_index_urls
import bookmark.urls as bookmark_urls
import accounts.urls as accounts_urls
from config import settings

urlpatterns = [
    path('', include(app_index_urls)),
    path('admin/', admin.site.urls),
    path('accounts/', include(accounts_urls)),
    path('bookmark/', include(bookmark_urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import ASCIIUsernameValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from django.apps import apps


class UsernameValidator(ASCIIUsernameValidator):
    regex = r'^[\w-]+\Z'
    message = _(
        '영문자, 숫자, - 또는 _만 사용 가능합니다.'
    )


class UserProfile(AbstractUser):
    def _upload_to(instance, filename): # ToDo: 업로드 하는 경로 유의하기
        return 'profile_images/%s/%s' % (instance.username, filename)

    username_validator = UsernameValidator()
    username = models.CharField(
        _('아이디'),
        max_length=36,
        unique=True,
        help_text= _('필수 항목. 36자 이하로 영문자, 숫자, - 또는 _만 사용 가능합니다.'),
        validators=[username_validator],
        error_messages={
            'unique': _("해당 아이디는 이미 존재합니다."),
        }
    )
    nickname = models.CharField(
        _('닉네임'),
        max_length=36,
        unique=True,
        help_text=_('필수 항목. 36자 이하로 영문자, 숫자, - 또는 _만 사용 가능합니다.'),
        validators=[username_validator],
        error_messages={
            'unique': _("해당 닉네임은 이미 존재합니다."),
        }
    )
    email = models.EmailField(_('이메일'), blank=True)

    name = models.CharField(_('이름'), max_length=15, blank=True)
    first_name = last_name = None

    birth_date = models.DateField(_('생년월일'), blank=True, null=True)
    belong_to = models.CharField(_('소속'), max_length=30, blank=True, null=True)

    profile_image = models.ImageField(_('프로필 이미지'), upload_to=_upload_to, default='profile_images/no_image.png')
    state_message = models.CharField(_('상태 메시지'), max_length=50, blank=True, null=True)

    favorite_lists = models.ManyToManyField('bookmark.BookmarkList', related_name="fan_of_list", blank=True)
    favorite_items = models.ManyToManyField('bookmark.BookmarkItem', related_name="fan_of_item", blank=True)

    # REQUIRED_FIELDS = [email]
    # username과 password는 required, AbstractUser에서는 email도

    def is_list_fan(self, _list_pk):
        BookmarkList = apps.get_model('bookmark.BookmarkList')
        _list = BookmarkList.objects.get(pk=_list_pk)
        if _list:
            if _list.fan_of_list.filter(pk=self.pk):
                return {
                    'list': _list,
                    'is_fan': True,
                }

        return None # ToDo: raise 404

    def is_item_fan(self, _item_pk):
        BookmarkItem = apps.get_model('bookmark.BookmarkItem')
        _item = BookmarkItem.objects.get(pk=_item_pk)
        if _item:
            if _item.fan_of_item.filter(pk=self.pk):
                return {
                    'item': _item,
                    'is_fan': True,
                }

        return None  # ToDo: raise 404

    def is_following(self, _owner_nickname):
        _owner = UserProfile.objects.filter(nickname=_owner_nickname).get()
        return self.following.filter(following=_owner).count()


class Follower(models.Model):
    follower = models.ForeignKey(UserProfile, related_name='following', on_delete=models.CASCADE)
    following = models.ForeignKey(UserProfile, related_name='follower', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('follower', 'following')

    def __unicode__(self):
        return u'%s follows %s' % (self.follower, self.following)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm, PasswordResetForm, \
    SetPasswordForm
from django.utils.translation import gettext_lazy as _

from accounts.models import UserProfile
from config.library.forms import add_style


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        max_length=36,
        label=_('아이디'),
        widget=forms.TextInput(
            attrs={'class': 'form-control mt-2'},
        ),
    )
    password = forms.CharField(
        label=_('비밀번호'),
        widget=forms.PasswordInput(
            attrs={'class': 'form-control mt-2'},
        )
    )

    error_messages = {
        'invalid_login': _(
            "아이디나 비밀번호를 확인해주세요"
        ),
        'inactive': _("이 계정은 사용정지 되었습니다"),
    }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(LoginForm, self).__init__(*args, **kwargs)
        # TODO: 이거 왜 그런거지? - AuthForm이 이미 request를 가지고 있다고 본거 같기도

    class Meta:
        model = UserProfile
        fields = ['username', 'password']
        # TODO: add validator


class RegistrationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)

        add_style(self.fields)

    class Meta:
        model = UserProfile
        fields = ('username', 'nickname', 'email', 'password1', 'password2', 'name',
                    'birth_date', 'belong_to', 'state_message', 'profile_image')
        widgets = {
            'birth_date': forms.DateInput(attrs={'type': 'date'})
        }


class PWChangeForm(PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)

        add_style(self.fields)


class PWResetEmailForm(PasswordResetForm):

    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)

        add_style(self.fields)

        email = self.fields['email']
        email.label = '이메일'
        email.help_text = \
            '아래의 이메일로 안내 메시지가 전송됩니다. '\
            '회원가입 시 입력한 이메일을 입력해주세요.'


class PWResetForm(SetPasswordForm):
    def __init__(self, user, *args, **kwargs):
        super().__init__(user, *args, **kwargs)

        add_style(self.fields)

accounts/views.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import FormView

from accounts.forms import PWChangeForm, RegistrationForm, PWResetEmailForm, LoginForm, PWResetForm


# def index(request): # temporary
#    return HttpResponse('Hello')

class LoginForbiddenMixin(UserPassesTestMixin):
    # login_url = reverse_lazy('bookmark:index')

    def test_func(self):
        return not self.request.user.is_authenticated
        # ToDo: 403 에러 핸들러, alert('이미 로그인되어있습니다');


class LoginView(LoginForbiddenMixin, auth_views.LoginView):
    template_name = 'accounts/login.html'
    form_class = LoginForm


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    next_page = reverse_lazy('accounts:logout_success')
    # ToDo: next_page LoginRequiredMixin에 활용


def logout_success(request):
    if not request.user.is_authenticated:
        return render(request, 'accounts/logout_success.html')
    # TODO: redirect


def register_success(request):
    if not request.user.is_authenticated:
        return render(request, 'accounts/register_success.html')
    # TODO: redirect


class RegistrationView(LoginForbiddenMixin, FormView):
    template_name = 'accounts/registration.html'
    success_url = reverse_lazy('accounts:register_success')
    form_class = RegistrationForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class CustomPWChangeView(LoginRequiredMixin, auth_views.PasswordChangeView):
    template_name = 'accounts/password_change.html'
    success_url = reverse_lazy('accounts:password_change_done')
    form_class = PWChangeForm


class PasswordChangeDoneView(auth_views.PasswordChangeDoneView):
    template_name = "accounts/password_change_success.html"


class PasswordResetView(LoginForbiddenMixin, auth_views.PasswordResetView):
    # ToDo: login_forbidden
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = 'accounts/password_reset_email.html'
    subject_template_name = 'accounts/password_reset_subject.txt'
    template_name = 'accounts/password_reset_form.html'
    form_class = PWResetEmailForm


class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    success_url = reverse_lazy('accounts:password_reset_complete')
    template_name = 'accounts/password_reset_confirm.html'
    form_class = PWResetForm


class PasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'

accounts/templates/accounts/login.html
{% extends 'form_base.html' %}
{% block title %}{{ block.super }}-로그인{% endblock %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
            <script>alert('{{ message }}');</script>
        {% endfor %}
    {% endif %}

    <div class="container">
        {% include 'back_button.html' %}

        {% with '로그인' as button_value %}
            {{ block.super }}
        {% endwith %}
    </div>
{% endblock %}

accounts/templates/accounts/logout_success.html
{% extends 'alert_success.html' %}
{% block message %}로그아웃 되었습니다{% endblock %}
{% block redirect_url %}{% url 'bookmark:index' %}{% endblock %}

accounts/templates/accounts/password_change.html
{% extends 'form_base.html' %}
{% block title %}{{ block.super }}-비밀번호 변경{% endblock %}
{% block content %}
    <div class="container">
        {% include 'back_button.html' %}

        {% with '비밀번호 변경' as button_value %}
            {{ block.super }}
        {% endwith %}
    </div>
{% endblock %}

accounts/templates/accounts/password_change_success.html
{% extends 'alert_success.html' %}
{% block message %}비밀번호가 변경되었습니다{% endblock %}
{% block redirect_url %}{% url 'bookmark:index' %}{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'alert_success.html' %}
{% block message %}비번이 재설정되었습니다{% endblock %}
{% block redirect_url %}{% url 'accounts:login' %}{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'form_base.html' %}
{% block title %}{{ block.super }}-비밀번호 변경{% endblock %}
{% block content %}
    <div class="container">
         <a href="{% url 'bookmark:index' %}" class="btn btn-info mb-3">
            홈
        </a>

        {% with '비밀번호 변경' as button_value %}
            {{ block.super }}
        {% endwith %}
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% block title %}{{ block.super }}-메일 전송 완료{% endblock %}
{% block content %}
    <div class="container">
        <div class="offset-md-3 col-md-6">
            <h2 class="text-info mb-3">
                메일이 전송되었습니다!
            </h2>
            <p>
                계정에 등록된 이메일로 비밀번호를 설정하기 위한 안내 사항을 보냈습니다. 곧 메일을 받으실 것입니다.
                만약 이메일을 받지 못하였다면, 등록하신 이메일을 다시 확인하시거나 스팸 메일함을 확인해주세요.
            </p>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
비밀번호를 바꾸고 싶어? 여기로 따라와!
http://localhost:8000{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

accounts/templates/accounts/password_reset_form.html
{% extends 'form_base.html' %}
{% block title %}{{ block.super }}-비번 초기화{% endblock %}
{% block content %}
    <div class="container">
        {% include 'back_button.html' %}

        {% with '메일 전송' as button_value %}
            {{ block.super }}
        {% endwith %}
    </div>
{% endblock %}

accounts/templates/accounts/register_success.html
{% extends 'alert_success.html' %}
{% block message %}회원가입 성공!{% endblock %}
{% block redirect_url %}{% url 'accounts:login' %}{% endblock %}

accounts/templates/accounts/registration.html
{% extends 'base.html' %}
{% block title %}{{ block.super }}-회원가입{% endblock %}
{% block content %}
    <div class="container">
        {% include 'back_button.html' %}

        <div class="offset-md-3 col-md-6 offset-lg-4 col-lg-4">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% if form.errors %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}

                {% for field in form %}
                    <!-- TODO: errors 어떻게 표시? -->
                    <ul>
                        {% for error in field.errors %}
                            <li class="text-danger">{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {{ field.label }}<br/>
                    {{ field }}<br/>
                    {% if field.help_text %}
                        <small class="text-warning">{{ field.help_text }}</small><br />
                    {% endif %}
                {% endfor %}

                <img id="profile_image_preview" src="http://www.clker.com/cliparts/d/L/P/X/z/i/no-image-icon-hi.png"
                     width="150" height="150" class="rounded border border-primary"/>

                <input type="submit" value="회원가입" class="btn btn-success w-100 my-3" />
            </form>
        </div>
    </div>
{% endblock %}
{% block scripts %}
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#profile_image_preview').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

    $("input[name='profile_image']").change(function(){
        readURL(this);
    });
</script>
{% endblock %}