accounts/urls.py
from django.urls import path, reverse_lazy

from accounts.views import LoginView, LogoutView, logout_success, RegistrationView, register_success, \
    CustomPWChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from config.library.views import custom_user_passes_test, custom_login_required

app_name = 'accounts'

urlpatterns = [
    # path('', accounts_views.index, name="index"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('logout-success/', logout_success, name="logout_success"),
    path('register/', RegistrationView.as_view(), name="register"),
    path('register-success/', register_success, name="register_success"),

    path('password-change/', CustomPWChangeView.as_view(), name="password_change"),
    path('password-change/done/', PasswordChangeDoneView.as_view(), name="password_change_done"),

    path('password-reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset/done/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import app_index.urls as app_index_urls
import bookmark.urls as bookmark_urls
import accounts.urls as accounts_urls
from config import settings

urlpatterns = [
    path('', include(app_index_urls)),
    path('admin/', admin.site.urls),
    path('accounts/', include(accounts_urls)),
    path('bookmark/', include(bookmark_urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/alert_success.html
<script>
    window.onload = function() {
        alert("{% block message %}{% endblock %}");
        location.href = "{% block redirect_url %}{% endblock %}";
    }
    // TODO: template은 프론트엔드 로직인데 과한 include인가?
</script>

templates/back_button.html
<button class="btn btn-info mb-3" onclick="window.history.back()">
    <i class="fas fa-arrow-left"></i> 뒤로 가기
</button>

templates/base.html
<!doctype html>
<html lang="ko" style="height: 100%; ">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
        integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    {% block css %}{% endblock %}

    <title>{% block title %}북마크{% endblock %}</title>
</head>

<body>
    <header style="background-color: #222222;">
        <nav class="container-fluid px-sm-5 mb-3 navbar navbar-expand-lg navbar-dark">
            <h2 class="col-3 pl-0"><a href="{% url 'index' %}" class="navbar-brand">Django Bookmark</a></h2>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler"
                aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="col-9 justify-content-end collapse navbar-collapse" id="navbarToggler">
                <ul class="navbar-nav">
                    {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'accounts:login' %}" class="nav-link w-40">로그인</a>
                    </li>
                    <li class="nav-item disabled">
                        <a href="{% url 'accounts:register' %}" class="nav-link">회원가입</a>
                    </li>
                    <li class="nav-item disabled">
                        <a href="{% url 'accounts:password_reset' %}" class="nav-link">비밀번호 리셋</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{% url 'accounts:logout' %}" class="nav-link">로그아웃</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'accounts:password_change' %}" class="nav-link">비밀번호 변경</a>
                    </li>
                    {% endif %}

                    <li class="nav-item">
                        <button class="btn btn-primary nav-link text-white" id="connect-wallet-button"
                            onclick="openPopup()">Connect
                            Wallet</button>
                    </li>
                    {% load static %}
                </ul>
            </div>
        </nav>
    </header>

    <div class="container mb-5">
        <div class="accordion border-bottom" id="accordionExample">
            <div class="card">
                <div class="card-header" id="headingOne">
                    <h2 class="mb-0">
                        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne"
                            aria-expanded="true" aria-controls="collapseOne" style="text-decoration: none;">
                            how it works
                        </button>

                    </h2>
                </div>

                <div id="collapseOne" class="collapse show" aria-labelledby="headingOne"
                    data-parent="#accordionExample">
                    <div class="card-body">
                        <p>
                            /bookmark/ => 자신의 북마크 리스트<br />
                            /bookmark/test_001(~010)/ => 공개로 설정한 북마크 리스트
                        </p>
                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-header" id="headingTwo">
                    <h2 class="mb-0">
                        <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                            data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo"
                            style="text-decoration: none;">
                            To Do
                        </button>
                    </h2>
                </div>

                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                    <div class="card-body">
                        <p>
                        <ul>
                            <li>댓글</li>
                            <li>정렬/검색</li>
                            <li>race condition</li>
                            <li>배포 방법</li>
                        </ul>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer class="text-white px-5 py-4" style="background-color: #222222;">
        <div>
            &copy;2019 nab5m - All rights reserved.<br />
            nab5m.pythonanywhere.com is maintained by JunYoung, Kim.<br />
        </div>
        <div class="text-right" style="font-size: 1.3rem;">
            <a href="http://github.com/nab5m/" target="_blank" class="text-white p-1" style="text-decoration: none;">
                <i class="fab fa-github"></i>
            </a>
            <a href="https://www.facebook.com/profile.php?id=100011737238706" target="_blank" class="text-white p-1"
                style="text-decoration: none;">
                <i class="fab fa-facebook"></i>
            </a>
        </div>
    </footer>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

    {% block scripts %}{% endblock %}
    <script>
        if ($('body').height() < $('html').height()) {
            let $body = $('body');
            let $footer = $('footer');
            $body.css('min-height', '100%');
            $body.css('position', 'relative');

            $footer.css('position', 'absolute');
            $footer.css('bottom', '0');
            $footer.css('width', '100%');
        }
        function openPopup() {
            var height = 600;
            var width = 360;
            var topPosition = window.screenTop || window.screenY || 0;
            var rightPosition = window.screenLeft + window.innerWidth - width;

            var newWindow = window.open("", "", "height=" + height + ", width=" + width + ", top=" + topPosition + ", left=" + rightPosition + ", scrollbars=no");
            newWindow.location.href = "{% url 'popup_view' %}";
        }

    </script>
</body>

</html>

templates/form_base.html
{% extends 'base.html' %}
{% block content %}
    <div class="offset-md-3 col-md-6 offset-lg-4 col-lg-4">
        <form method="post">
            {% csrf_token %}
            {% if form.errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}

            {% for field in form %}
                <!-- TODO: errors 어떻게 표시? -->
                <ul>
                    {% for error in field.errors %}
                        <li class="text-danger">{{ error }}</li>
                    {% endfor %}
                </ul>
                {{ field.label }}<br/>
                {{ field }}<br/>
                {% if field.help_text %}
                    <small class="text-warning">{{ field.help_text }}</small><br />
                {% endif %}
            {% endfor %}

            <input type="submit" value="{{ button_value }}" class="btn btn-success w-100 my-3" />
        </form>
    </div>
{% endblock %}